spring:
  application:
    name: testing


server:
  tomcat:
    threads:
      max: 2           # Only 1 thread! / worker
      min-spare: 2     # Minimum 1 thread / worker
    accept-count: 2   # Queue lo max 2 requests wait cheyochu
  port: 8084
