spring:
  application:
    name: notification-service-app # Eureka lo ee peru tho register avuthundi

  config:
    import: optional:configserver:http://localhost:8888

  # ----------------------------------------------------
  # 1. KAFKA CONFIGURATION (The Post Box ðŸ“® Address)
  # ----------------------------------------------------
  kafka:
    consumer:
      # Kafka server address (default ga port 9092 lo run avuthundi)
      bootstrap-servers: localhost:9092
      # Ee consumer ye group ki chendindo cheppadaniki (oke message ni chala sarlu process cheyyakunda)
      group-id: notification-group
      # Kafka ki pampina message format (Key=String, Value=String)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8084 # Ee service kosam kotha port



# ----------------------------------------------------
# 2. EUREKA CONFIGURATION
# ----------------------------------------------------
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#logging:
#  pattern:
#    # Simple, clean console pattern - no horizontal scrolling needed
#    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) : %msg%n"
#    # Detailed file pattern with full logger names
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{50} : %msg%n"
# application.yml (all services)
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus